version: '3'

services:
  postgres:
    image: postgres:16
    command: '-d 1' # set debug-level
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
  neon-proxy:
    image: local-neon-http-proxy:latest
    build:
      context: docker
      dockerfile: Dockerfile
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/main
      - ENABLE_TELEMETRY=false
    ports:
      - '4444:4444'
    depends_on:
      - postgres
    
volumes:
  db_data: