export const Navigation = {
  HOME: '/home',
  PRICING: '/pricing',
  // Requires authentication, if not will redirect to HOME
  DASHBOARD_ROOT: '/',
  DASHBOARD_COMPONENTS: '/components',
  DASHBOARD_COMPONENTS_NEW: '/components/new',
  DASHBOARD_RELEASES: '/releases',
  DASHBOARD_INTEGRATIONS: '/integrations',
  DASHBOARD_SETTINGS: '/settings',
  DASHBOARD_BILLING: '/billing',
} as const;

export type NavigationItem = (typeof Navigation)[keyof typeof Navigation];

export const dashboardRoute = (
  slug: string | string[],
  path?: NavigationItem
) =>
  `${Navigation.DASHBOARD_ROOT}${typeof slug === 'string' ? slug : slug[0]}${path ? path : ''}`;

export const RootLevelPathRegex = /^[^/]*\/[^/]*$/;

export const RootLevelPaths = Object.values(Navigation)
  .filter((path) => path.match(RootLevelPathRegex))
  .map((path) => path.substring(1));

const AlphabetArray = Array.from(Array(26))
  .map((_, i) => i + 65)
  .map((x) => String.fromCharCode(x));

const NumberArray = [...Array(10).keys()].map((x) => x.toString());

export const DisallowedSlugs = [
  ...RootLevelPaths,
  ...AlphabetArray,
  ...NumberArray,
  'new',
  'settings',
  'billing',
  'integrations',
  'releases',
  'components',
  'home',
  'pricing',
  'dashboard',
  'sign-in',
  'sign-up',
  'sign-out',
  'forgot-password',
  'reset-password',
  'verify-email',
  'password',
  'email',
  'username',
  'name',
  'change-password',
  'change-email',
  'change-username',
  'change-name',
  'change-phone-number',
  'change-profile-picture',
  'forgot',
  'reset',
  'verify',
  'change',
  'user',
  'users',
  'profile',
  'profiles',
  'organization',
  'organizations',
  'workspace',
  'workspaces',
  'team',
  'teams',
  'project',
  'projects',
  'error',
  'errors',
  'not-found',
  'not-found-error',
  '404',
  'undefined',
  'null',
  'nan',
  'false',
  'true',
  '-1',
  '0',
  'stripe',
  'webhook',
  'webhooks',
  'api',
  'apis',
  'graphql',
  'rest',
  'v0',
  'v1',
  'v2',
  'v3',
  'v4',
  'v5',
  'v6',
  'v7',
  'v8',
  'v9',
  'endpoint',
  '-',
  '--',
  '---',
  'verification',
  'verifications',
  'auth',
  'authentication',
  'authorize',
  'login',
  'logout',
  'register',
  'signup',
  'signin',
  'token',
  'tokens',
  'session',
  'sessions',
  'cookie',
  'cookies',
  'local-storage',
  'session-storage',
  'indexed-db',
  'web-storage',
  'web-worker',
  'service-worker',
  'shared-worker',
  'worker',
  'workers',
  'cache',
  'push',
  'notification',
  'notifications',
  'message',
  'messages',
  'email',
  'emails',
  'sms',
  'mms',
  'push-notification',
  'push-notifications',
  'apikeys',
  'api-key',
  'about',
  'faq',
  'contact',
  'contact-us',
  'ask',
  'support',
  'help',
  'docs',
  'documentation',
  'blog',
  'news',
  'updates',
  'changelog',
  'terms',
  'terms-of-service',
  'privacy',
  'privacy-policy',
  'terms',
  'old',
  'function',
  'object',
  'array',
  'queue',
  'stack',
  'keys',
  '.well-known',
  'well-known',
  'robots',
  'app',
];
