export const ErrorCodes = {
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  INVALID_SESSION_CLAIMS: 'INVALID_SESSION_CLAIMS',
  STRIPE_CUSTOMER_DELETED: 'STRIPE_CUSTOMER_DELETED',
  STRIPE_CUSTOMER_NOT_LINKED: 'STRIPE_CUSTOMER_NOT_LINKED',
  INTERNAL_MISCONFIGURATION: 'INTERNAL_MISCONFIGURATION',
} as const;
