import { StatusCodes } from 'http-status-codes';

export const ErrorCodeTypes = {
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  RESOURCE_HAS_DEPENDENTS: 'RESOURCE_HAS_DEPENDENTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  WORKSPACE_SLUG_UNAVAILABLE: 'WORKSPACE_SLUG_UNAVAILABLE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_SESSION_CLAIMS: 'INVALID_SESSION_CLAIMS',
  STRIPE_CUSTOMER_DELETED: 'STRIPE_CUSTOMER_DELETED',
  STRIPE_CUSTOMER_NOT_LINKED: 'STRIPE_CUSTOMER_NOT_LINKED',
  STRIPE_UNHANDLED_WEBHOOK_EVENT: 'STRIPE_UNHANDLED_WEBHOOK_EVENT',
  STRIPE_WEBHOOK_FAILURE: 'STRIPE_WEBHOOK_FAILURE',
  STRIPE_PRICE_NOT_ACTIVE: 'STRIPE_PRICE_NOT_ACTIVE',
  STRIPE_PRICE_NOT_SUPPORTED: 'STRIPE_PRICE_NOT_SUPPORTED',
  STRIPE_CHECKOUT_SESSION_CREATION_FAILURE:
    'STRIPE_CHECKOUT_SESSION_CREATION_FAILURE',
  STRIPE_CHECKOUT_SESSION_STALE: 'STRIPE_CHECKOUT_SESSION_STALE',
  INTERNAL_MISCONFIGURATION: 'INTERNAL_MISCONFIGURATION',
  RECORD_DELETE_FAILURE: 'RECORD_DELETE_FAILURE',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',
} as const;

export type ErrorCode = {
  type: keyof typeof ErrorCodeTypes;
  statusCode: StatusCodes;
};

export const ErrorCodes: Record<keyof typeof ErrorCodeTypes, ErrorCode> = {
  // RESOURCE STATES
  RESOURCE_ALREADY_EXISTS: {
    type: 'RESOURCE_ALREADY_EXISTS',
    statusCode: StatusCodes.CONFLICT,
  },
  RESOURCE_NOT_FOUND: {
    type: 'RESOURCE_NOT_FOUND',
    statusCode: StatusCodes.NOT_FOUND,
  },
  RESOURCE_HAS_DEPENDENTS: {
    type: 'RESOURCE_HAS_DEPENDENTS',
    statusCode: StatusCodes.CONFLICT,
  },
  WORKSPACE_NOT_FOUND: {
    type: 'WORKSPACE_NOT_FOUND',
    statusCode: StatusCodes.NOT_FOUND,
  },
  WORKSPACE_SLUG_UNAVAILABLE: {
    type: 'WORKSPACE_SLUG_UNAVAILABLE',
    statusCode: StatusCodes.BAD_REQUEST,
  },
  RECORD_DELETE_FAILURE: {
    type: 'RECORD_DELETE_FAILURE',
    statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
  },
  INVALID_REQUEST: {
    type: 'INVALID_REQUEST',
    statusCode: StatusCodes.BAD_REQUEST,
  },

  // AUTHENTICATION
  USER_NOT_FOUND: {
    type: 'USER_NOT_FOUND',
    statusCode: StatusCodes.NOT_FOUND,
  },
  ORGANIZATION_NOT_FOUND: {
    type: 'ORGANIZATION_NOT_FOUND',
    statusCode: StatusCodes.NOT_FOUND,
  },
  INVALID_SESSION_CLAIMS: {
    type: 'INVALID_SESSION_CLAIMS',
    statusCode: StatusCodes.UNAUTHORIZED,
  },

  // STRIPE
  STRIPE_CUSTOMER_DELETED: {
    type: 'STRIPE_CUSTOMER_DELETED',
    statusCode: StatusCodes.NOT_FOUND,
  },
  STRIPE_CUSTOMER_NOT_LINKED: {
    type: 'STRIPE_CUSTOMER_NOT_LINKED',
    statusCode: StatusCodes.NOT_FOUND,
  },
  STRIPE_UNHANDLED_WEBHOOK_EVENT: {
    type: 'STRIPE_UNHANDLED_WEBHOOK_EVENT',
    statusCode: StatusCodes.BAD_REQUEST,
  },
  STRIPE_WEBHOOK_FAILURE: {
    type: 'STRIPE_WEBHOOK_FAILURE',
    statusCode: StatusCodes.BAD_REQUEST,
  },
  STRIPE_CHECKOUT_SESSION_CREATION_FAILURE: {
    type: 'STRIPE_CHECKOUT_SESSION_CREATION_FAILURE',
    statusCode: StatusCodes.BAD_REQUEST,
  },
  STRIPE_CHECKOUT_SESSION_STALE: {
    type: 'STRIPE_CHECKOUT_SESSION_STALE',
    statusCode: StatusCodes.BAD_REQUEST,
  },
  STRIPE_PRICE_NOT_ACTIVE: {
    type: 'STRIPE_PRICE_NOT_ACTIVE',
    statusCode: StatusCodes.BAD_REQUEST,
  },
  STRIPE_PRICE_NOT_SUPPORTED: {
    type: 'STRIPE_PRICE_NOT_SUPPORTED',
    statusCode: StatusCodes.BAD_REQUEST,
  },

  // GENERIC
  INTERNAL_MISCONFIGURATION: {
    type: 'INTERNAL_MISCONFIGURATION',
    statusCode: StatusCodes.NOT_IMPLEMENTED,
  },
  UNHANDLED_ERROR: {
    type: 'UNHANDLED_ERROR',
    statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
  },
} as const;
