name: Packages Build

on:
  pull_request:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    if: github.repository == 'versioning-app/versioning.app'
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn

      - name: Ensure packages build successfully
        run: yarn build:packages
